id: 9df027c530a24a24bd7fa43f0aa68818
initial_creation_type: ocr
source_metadata:
  volumes:
    e8336215c40148b8a1187f9f6ddcc595:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: ''
      total_pages: 1044
      volume_number: 38
